services:
  mysql:
    image: mariadb
    container_name: ctf-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: if674_ctf
    ports:
      - "3306:3306"  # Expose MySQL port on the host machine
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge

